function [ tablePlayers_fromDB, tablePlayers_forTournament ] = generateTable()

if nargin < 1
    disp('TO DO')
end

% tablePlayers_fromDB  = table(...
%     {'temp'},...
%     {'temp'},...
%     {'None'},...
%     {'None'},...
%     'VariableName', {'name', 'familyName', 'country', 'town'});

tablePlayers_fromDB  = table(...
    {'LYP41'; 'G59S5'; 'VFHO0'; '32LTD'; 'EEYRG'; 'RFB4U'}, ...
    {'cao'; 'david'; 'chris'; 'nathan'; 'adrian'; 'cal'},...
    {'do'; 'lang'; 'froche'; 'mansard'; 'peyrat'; 'chiu'},...
    {'malganis35'; 'chinois'; 'Krys'; 'Nat'; 'Midori'; 'Cal'},...
    {'france'; 'uk'; 'france'; 'it'; 'es'; 'ge'},...
    {'rennes'; 'london'; 'avignon'; 'rome'; 'madrid'; 'berlin'},...
    {'ZnT'; 'SAO'; 'FZ'; 'MG'; 'MD'; 'GC'}, ...
    'VariableName', {'WSCode', 'name', 'familyName', 'pseudo', 'country', 'town', 'serie'});


% tablePlayers_forTournament = table(...
%     {'temp'},...
%     {'temp'},...
%     {'None'},...
%     {'None'},...
%     'VariableName', {'name', 'familyName', 'country', 'town'});

tablePlayers_forTournament  = table(...
    {'temp'},...
    {'temp'},...
    {'temp'},...
    {'temp'},...
    {'temp'},...
    {'temp'},...
    {'temp'},...
    'VariableName', {'WSCode', 'name', 'familyName', 'pseudo', 'country', 'town', 'serie'});


end