function showHandlesTournament(handles, mode)

set(handles.BUT_addPlayer, 'Visible', mode)
set(handles.BUT_removePlayer, 'Visible', mode)
set(handles.TEXT_playerForTournament, 'Visible', mode)
set(handles.TAB_players_Tournament, 'Visible', mode)
set(handles.POP_sortByTournament, 'Visible', mode)
set(handles.POP_sortOrderTournament, 'Visible', mode)
set(handles.TEXT_search, 'Visible', mode)
set(handles.EDIT_searchPlayerTournament, 'Visible', mode)
set(handles.BUT_beginTournament, 'Visible', mode)
set(handles.TEXT_tournamentName, 'Visible', mode)
set(handles.EDIT_tournamentName, 'Visible', mode)
set(handles.TEXT_tournamentInformation, 'Visible', mode)
set(handles.BUT_saveAsLocalDB, 'Visible', mode)
set(handles.BUT_editPlayerAdditionnalInformation, 'Visible', mode)
set(handles.BUT_addPlayerBarcode, 'Visible', mode)
set(handles.BUT_uniqueWSCode, 'Visible', mode)
