function [ tablePlayers_fromDB, tablePlayers_forTournament ] = generateTable()

if nargin < 1
    disp('TO DO')
end

% tablePlayers_fromDB  = table(...
%     {'temp'},...
%     {'temp'},...
%     {'None'},...
%     {'None'},...
%     'VariableName', {'name', 'familyName', 'country', 'town'});

tablePlayers_fromDB  = table(...
    {'LYP41'; 'G59S5'; 'VFHO0'; '32LTD'; 'EEYRG'; 'RFB4U'}, ...
    {'cao'; 'xav'; 'chris'; 'nathan'; 'adrian'; 'cal'},...
    {'do'; 'chab'; 'froche'; 'mansard'; 'peyrat'; 'chiu'},...
    {'france'; 'uk'; 'france'; 'it'; 'es'; 'ge'},...
    {'rennes'; 'london'; 'avignon'; 'rome'; 'madrid'; 'berlin'},...
    'VariableName', {'WSCode', 'name', 'familyName', 'country', 'town'});


tablePlayers_forTournament = table(...
    {'temp'},...
    {'temp'},...
    {'None'},...
    {'None'},...
    'VariableName', {'name', 'familyName', 'country', 'town'});

end